version: '3.9'

services:
  vue:
    image: node:current-alpine
    container_name: vue
    tty: true
    volumes:
      - ./:/app
    expose:
      - 8888
    ports:
      - '8888:80'
      - '443:443'
    command: bash -c "cd /app && npm start"
