version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
